#application: www-postpal
#clear
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

skip_files:
- ^config.toml$
- ^static/config.yaml$
- ^static/Directorylisting.txt$
- ^content$
- ^layouts$
- ^data$
- ^appadmin$
- ^public$
- ^(.*/)?\..*$

  # dev_appserver.py ~/projects/www-postpal
  # nope-application: www-postpal
  # nope-version: 1
