baseurl = "https://fb.postpal.com/"
title = "Mentoring for the digitally crippled"
[taxonomies]
tag = "tags"
post = "posts"
[Params]
#cssurl = "//port-1313.www-postpal-githubdklongley901739.codeanyapp.com/"
cssurl = "https://fb.postpal.com/"